### ISSUE TITLE
Fix Titan

### ISSUE THREAD

**Issue by lowtorola** [battlecode/galaxy#786]
Titan seems to not be working, and thus we cannot download resumes in the frontend2. Need to fix in order to launch, hence this falls under the alpha milestone.

Work on this issue fixes #627 as well :rocket:

**Comment by n8kim1** [comment]
Lowell and I tried for 2.5 hours (so like 5 dev-hours) and we couldn't get things working, but here's a listing for posterity:

Stuff we did
- Make new triggers 
- Have the account that runs Eventarc be Google's designated service account, not a new service account under our control
  - this is the default if you make a new trigger
  - `Cloud Pub/Sub needs the role roles/iam.serviceAccountTokenCreator granted to service account service-830784087321@gcp-sa-pubsub.iam.gserviceaccount.com on this project to create identity tokens. You can change this later.`
  - `This trigger needs the role roles/eventarc.eventReceiver granted to service account 830784087321-compute@developer.gserviceaccount.com to receive events via Google sources.`
- manually set min runtime instances , so that Titan is actually up
- Give the service account "eventarc event receiver" iam role and storage admin
- **Important: Terraform apply would reset all these changes! These changes were made manually**

State of things now
- Event arc doesfire
- But Titan fails to run the thing. Titan seems to throw a 403 somewhere. Unsure where or why...

What we thought of to try later:
- In terraform, set In order to use Cloud Storage triggers in Cloud Functions (2nd gen), the Cloud Storage service agent must have the Pub/Sub Publisher (roles/pubsub.publisher) IAM role on your project. This requirement does not apply to Cloud Functions (1st gen).
  - do we have to manually? shouldn't this be in terraform somehow???
- check backend logs
- try staging?
- rewrite entirely in pub/sub way?
- which service ?? siarnaq or titan?
- is mitbattlecode-production-secure multiregion on accident?

**Comment by lowtorola** [comment]
FIXED!!!! To fix the mysterious 403, I followed the link in the log error message to [this troubleshooting guide](https://cloud.google.com/run/docs/troubleshooting#unauthorized-client):
Adding the suggested permission (Cloud Run Invoker) to the service account responsible for creating the EventArc file metadata update trigger resolved the 403 error.
<img width="923" alt="Screenshot 2024-05-06 at 4 33 39 PM" src="https://github.com/battlecode/galaxy/assets/44183219/9090377f-04cd-4ac2-8107-da03c7f33e2b">

**Comment by lowtorola** [comment]
TODO: verify that Titan is now checking strategy reports and code submissions before closing!
