### ISSUE TITLE
Routing Lockdown

### ISSUE THREAD

**Issue by lowtorola** [battlecode/galaxy#794]
Currently, navigating to pages that don't match our pattern for navigation bring up the homepage and potentially throw a server error toast (because we are trying to parse an episode that doesn't exist). The following rules should be implemented:
 - [x] Episode info must be loaded before the home page renders 
  - [x] Await load episode info in the episodeLoader
  - [x] Indicate that the episode is loading in the episode switcher while it verifies that the episode exists
 - [x] If the episode info load fails, redirect to 404 not found page
 - [x] If the page load fails, redirect to 404 not found page
 - [x] Navigating to "localhost:3000" redirects to current episode home page

**Comment by acrantel** [comment]
just to clarify - does "redirect to 404 not found page" mean that we should navigate to something like `/notfound` or does it mean that we will display the "page not found" message on the screen? currently it seems to be the "page not found" message. 

(if the current behavior is the expected behavior, then this PR lgtm!)
